#!/usr/bin/python3

import sqlite3
import jdatetime
import click
import time

# defaults. should change later
sql_filename = 'hesab.sql'
tablename = 'standard'

connection = sqlite3.connect(sql_filename)
sql_cursor = connection.cursor()

def list_entries():
    entries = sql_cursor.execute(f'SELECT * FROM {tablename}')
    for i, entry in enumerate(entries):
        name = entry[0]
        date = jdatetime.datetime.fromtimestamp(int(entry[1])).date()
        value = entry[2]
        print(i + 1, name, date, value)

def add_entry(name, date, value):
    sql_cursor.execute(f'''INSERT INTO {tablename} VALUES(?,?,?)''', [name, date, value])

def remove_entry(entry_id):
    sql_cursor.execute(f"""DELETE FROM {tablename} LIMIT {entry_id-1},{1};""")

