#!/usr/bin/env python

import sqlite3
import jdatetime
import click
import time
from rich.table import Table
from rich import print as rprint

# defaults. should change later
sql_filename = 'hesab.sql'
tablename = 'standard'

connection = sqlite3.connect(sql_filename)
sql_cursor = connection.cursor()

def create_database():
    sql_filename = 'hesab.sql'
    connection = sqlite3.connect(sql_filename)
    sql_cursor = connection.cursor()
    tablename = 'standard'
    sql_cursor.execute(f'''CREATE TABLE IF NOT EXISTS {tablename} (
        date DATETIME,
        name TEXT,
        value REAL
        )''')
    connection.commit()


def get_entries_list():
    entries = sql_cursor.execute(f'SELECT * FROM {tablename}')
    entries_list = []
    for i, entry in enumerate(entries):
        # date = jdatetime.datetime.fromtimestamp(int(entry[0])).date()
        date = entry[0]
        name = entry[1]
        value = entry[2]
        entries_list.append((i + 1, date, name, value))
    return entries_list

def flatten_entries_date(entries):
    output = map(lambda entry:(entry[0], jdatetime.datetime.fromtimestamp(int(entry[1])).date(), entry[2], entry[3]), entries)
    return list(output)

def filter_entries_today(entries):
    entries = flatten_entries_date(entries)
    today_date = jdatetime.datetime.fromtimestamp(time.time()).date()
    output = filter(lambda entry:entry[1] == today_date, entries)
    return list(output)


def print_entries_list(entries):

    entries = filter_entries_today(entries)

    egg_price = 5 # how much is an egg today?

    table = Table(title="دخل‌وخرج‌ها", expand=True)

    table.add_column("اندیس", justify="right", style="cyan", no_wrap=True)
    table.add_column("تاریخ", justify="right", style="cyan", no_wrap=True)
    table.add_column("عنوان", style="magenta")
    table.add_column("مبلغ تومان‌ریال", justify="right", style="green")
    table.add_column(f"🥚={egg_price}", justify="right", style="green")

    for entry in entries:
        index = str(entry[0])
        date = entry[1].strftime("%y-%m-%d")
        name = entry[2]
        
        value = str(entry[3])
        value_egg = str((entry[3] / egg_price*100)//1/100)
        table.add_row(index, date, name, value, value_egg)

    rprint(table)        
    # print(f'{index}:   {date}    {name}   \t {value}')


def add_entry(date, name, value):
    sql_cursor.execute(f'''INSERT INTO {tablename} VALUES(?,?,?)''', [date, name, value])
    connection.commit()

def add_entry_with_date(name, value):
    date = time.time()
    add_entry(date, name, value)

def remove_entry(entry_id):
    sql_cursor.execute(f"""DELETE FROM {tablename} LIMIT {entry_id-1},{1};""")
    connection.commit()


@click.group()
def cli():
    pass

@cli.command()
@click.argument('name')
@click.argument('value')
def add(name, value):
    add_entry_with_date(name, value)
    click.echo(f'added {name} with {value}')

@cli.command("list")
def list_entries():
    entries = get_entries_list()
    print_entries_list(entries)
# remove_entry(1)

# list_entries()
if __name__ == '__main__':
    # create_database()
    cli()